<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panelvuelos [
        <!ELEMENT aeropuertos (aeropuerto)*>
        <!ELEMENT aeropuerto (nombre, vuelos*, fecha)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT vuelos (vuelo+)>
        <!ELEMENT vuelo (diario?, origen, destino, salida, llegada, estado)>
        <!ATTLIST vuelo codigo ID #REQUIRED>
        <!ATTLIST vuelo estado (C | E | R) "E">
        <!ELEMENT diario (#PCDATA)>
        <!ELEMENT origen (#PCDATA)>
        <!ELEMENT destino (#PCDATA)>
        <!ELEMENT salida (#PCDATA)>
        <!ELEMENT llegada (#PCDATA)>
        <!ELEMENT estado (#PCDATA)>
        <!ELEMENT fecha (#PCDATA)>

        ]

<aeropuertos>
    <aeropuerto>
        <nombre>AEROPUERTO JFK</nombre>
        <vuelos>
            <vuelo codigo="V22" estado="R">
                <diario>SI</diario>
                <origen>New York</origen>
                <destino>Chicago</destino>
                <salida>9:30</salida>
                <llegada>11:30</llegada>
            </vuelo>
        </vuelos>
        <vuelos>
            <vuelo codigo="V23" estado="C">
                <diario>NO</diario>
                <origen>New York</origen>
                <destino>Miami</destino>
                <salida>10:15</salida>
                <llegada>11:15</llegada>
            </vuelo>
        </vuelos>
        <fecha>20/12/2025</fecha>
    </aeropuerto>
</aeropuertos>






